### ISSUE TITLE
Tip for applying common scripts

### ISSUE THREAD

**Issue by TWiStErRob** [tomasbjerre/gradle-scripts#1]
```gradle
apply from: 'https://raw.githubusercontent.com/tomasbjerre/gradle-scripts/master/src/main/resources/java.gradle'
//etc...
```

you can save on `repositories`, `dependencies` and `classloader` magic

**Comment by tomasbjerre** [comment]
The reason for applying via jar and Maven repository is ta have them cached. So that I can build projects faster and when offline.
